theme: jekyll-theme-tactile

build:
  version: 0.0.11
  url:
    windows:
      x86: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model/archive/v1.0.zip
      x64: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model/archive/v1.0.zip
    macosx:
      x64: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model/archive/v1.0.tar.gz
    linux:
      x86: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model/archive/v1.0.tar.gz
      x64: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model/archive/v1.0.tar.gz
