theme: jekyll-theme-tactile

owner:
  name: Manuel Bogoni
  email: manuelbogoni@gmail.com
  first_published: 2017
  
navbar-links:
  About Me: "aboutme"
  Projects:
    - MCMM: "https://fluidmechanicsunipd.github.io/Meander-Centerline-Migration-Model/"
  Publications:
  Contacs:
  
author: "Manuel Bogoni"

repository: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model # code repository on Github

show_downloads: true # it should show buttons to download the code, but actually the link downloads the entire folder..

google_analytics:
