theme: jekyll-theme-tactile

# Name of website
title: MCMM
subtitle: Meander Centerline Migration Model

# Short description of your site
description: This repository contains the source codes of the numerical model developed by 
[Bogoni et al. WRR 2017](http://onlinelibrary.wiley.com/doi/10.1002/2017WR020726/abstract) 
and featured as AGU Research Spotlight by [EOS](https://doi.org/10.1029/2017EO078667).

owner:
  name: Manuel Bogoni
  email: manuelbogoni@gmail.com
  first_published: 2017
  
navbar-links:
  About Me: "aboutme"
  Projects:
    - MCMM: "https://fluidmechanicsunipd.github.io/Meander-Centerline-Migration-Model/"
  Publications:
  Contacs:
  
author: "Manuel Bogoni"

repository: https://github.com/FluidMechanicsUNIPD/Meander-Centerline-Migration-Model # code repository on Github

show_downloads: false # it should show buttons to download the code, but actually the link downloads the entire folder..

google_analytics:
